export const cursor = {
  pointer: "pointer",
  default: "default",
  text: "text",
  wait: "wait",
  move: "move",
  grab: "grab",
  grabbing: "grabbing",
  notAllowed: "not-allowed",
  help: "help",
  zoomIn: "zoom-in",
  zoomOut: "zoom-out",
  crosshair: "crosshair",
  none: "none",
  progress: "progress",
  cell: "cell",
  copy: "copy",
  alias: "alias",
  contextMenu: "context-menu",
  colResize: "col-resize",
  rowResize: "row-resize",
  allScroll: "all-scroll",
};
